### ISSUE TITLE
Plug-in not working with ios 4.0.0-dev

### ISSUE THREAD

**Issue by jvence** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#440]
Been testing iOS 4.0 and noticed that the plugin is not compatible. Here are the compile errors:

nl.x-services.plugins.socialsharing/SocialSharing.m:33:24: No visible @interface for 'UIView' declares the selector 'stringByEvaluatingJavaScriptFromString:'

and 

Plugins/nl.x-services.plugins.socialsharing/SocialSharing.m:606:24: Implicit declaration of function 'CDVNewBase64Decode' is invalid in C99

Any plans to make compatible with 4.0?

**Comment by EddyVerbruggen** [comment]
Thanks for letting me know, I'll do it shortly!

**Comment by jvence** [comment]
Sure. Here's the link to install ios 4.0 see https://shazronatadobe.wordpress.com

**Comment by EddyVerbruggen** [comment]
Fixed in 5.0.5.
