### ISSUE TITLE
Cannot build with WKWebView

### ISSUE THREAD

**Issue by daviddahl** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#341]
Not sure if this is a plugin error or a Telerik WKWebView plugin error:

mobileapp/platforms/ios/ZK/Plugins/nl.x-services.plugins.socialsharing/SocialSharing.m:33:24: error: no visible @interface for
      'UIView' declares the selector 'stringByEvaluatingJavaScriptFromString:'
  return [self.webView stringByEvaluatingJavaScriptFromString:@"window.plugins.socialsharing.iPadPopupCoordinates();"];

http://pastebin.com/Gy9sFRnC

I have Cordova 4.3.0 and "dev" platform.

**Comment by EddyVerbruggen** [comment]
Hi David, which version of WKWebView plugin are you on? I just created a new CLI project with the master branches of both and it worked fine on my iPad 8.3 emulator.

Or is your cordova-ios plaform perhaps 4.x? I have 3.8.

**Comment by daviddahl** [comment]
ddahl$ cordova platform
Installed platforms: ios 4.0.0-dev

Should I be on 3.8 instead?

**Comment by EddyVerbruggen** [comment]
4.0.0 seems to have some more nasty issues (so I heard).

This particular issue is caused by the fact that cordova-ios now uses a superclass of UIWebView to make it easy to swap in/out WKWebView. This means plugin authors like myself need to change some code to be compatible with the cordova-ios 4 release.

I'd recommend using 3.8 for now unless you want to be the canary in the colemine for other plugins as well.

But I thank you for reporting this, because obviously I need to change a few bits for cordova-ios 4.

**Comment by daviddahl** [comment]
Ok, looks like my build works with the Telerik wkwebview plugin & platform 3.8.x, but I cannot get a build working with the cordova one. Thanks!

**Comment by daviddahl** [comment]
Thanks for helping me out! I remember meeting you in Mountain View at Moz once! I'll see you around as I am doing a bunch of Cordova stuff;)

**Comment by irimon** [comment]
I'm having a similar  issue, but I'm using cordova iOS 3.8.

  no visible @interface for 'SocialSharing' declares the selector
      'cycleTheGlobalMailComposer'
    [self cycleTheGlobalMailComposer];

(followed by many other failures)

I had to install my plugin manually, as it was not recognized.

**Comment by daviddahl** [comment]
I usually remove the platform and add it again then add plugin build, add plugin build till it breaks

**Comment by irimon** [comment]
Thank! 
I tried that and it worked!
