### ISSUE TITLE
Issue with Ionic 3

### ISSUE THREAD

**Issue by echevarriafranco** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#1099]
Hi, since the last update I''m having an error trying to make the Ionic build for Android.
The last working version for me was 5.6.5.
The error is the following:

**BUILD FAILED in 1m 14s
28 actionable tasks: 28 executed
/builds/scm/petpo/petpo-fe-mobile/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/builds/scm/petpo/petpo-fe-mobile/platforms/android/app/src/main/java/nl/xservices/plugins/FileProvider.java:4: error: package androidx.core.content does not exist
public class FileProvider extends androidx.core.content.FileProvider {
                                                       ^
/builds/scm/petpo/petpo-fe-mobile/platforms/android/app/src/main/java/nl/xservices/plugins/SocialSharing.java:169: error: cannot find symbol
                fileUri = FileProvider.getUriForFile(webView.getContext(), cordova.getActivity().getPackageName()+".sharing.provider", new File(fileUri.getPath()));
                                      ^
  symbol:   method getUriForFile(Context,String,File)
  location: class FileProvider
/builds/scm/petpo/petpo-fe-mobile/platforms/android/app/src/main/java/nl/xservices/plugins/SocialSharing.java:285: error: cannot find symbol
                fileUri = FileProvider.getUriForFile(webView.getContext(), cordova.getActivity().getPackageName()+".sharing.provider", new File(fileUri.getPath()));
                                      ^
  symbol:   method getUriForFile(Context,String,File)
  location: class FileProvider
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors**

Only works on the version 5.6.5.
Please tell me if you need more information

**Comment by SailingSteve** [comment]
I have the same problem (all of the sudden) on Cordova Android

**Comment by SailingSteve** [comment]
Changing from 
     $ cordova plugin add https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin.git

To
      $ cordova plugin add cordova-plugin-x-socialsharing  

Resolved it for me. (I removed the plugin and reinstalled it without the url to github).
