### ISSUE TITLE
Linker and build errors when upgrading to 4.3.7

### ISSUE THREAD

**Issue by nitzanwilnai** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#201]
I get the following build and linker errors in my iOS PhoneGap Cordova app after upgrading.

Here is the installed plugin:
nl.x-services.plugins.socialsharing 4.3.7 "SocialSharing"

Build warning:
Plugins/nl.x-services.plugins.socialsharing/SocialSharing.m:18:8: Incompatible pointer to integer conversion initializing 'BOOL' (aka 'signed char') with an expression of type 'Class'

Linker errors:
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_MFMailComposeViewController", referenced from:
      objc-class-ref in SocialSharing.o
  "_OBJC_CLASS_$_MFMessageComposeViewController", referenced from:
      objc-class-ref in SocialSharing.o
  "_OBJC_CLASS_$_SLComposeViewController", referenced from:
      objc-class-ref in SocialSharing.o
  "_SLServiceTypeFacebook", referenced from:
      -[SocialSharing shareViaFacebook:] in SocialSharing.o
      -[SocialSharing shareViaFacebookWithPasteMessageHint:] in SocialSharing.o
  "_SLServiceTypeTwitter", referenced from:
      -[SocialSharing shareViaTwitter:] in SocialSharing.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

It compiled fine with 4.3.2 which is what I had previously. 

Any ideas?

Thanks!
