### PR TITLE
Androidx support

### PR DESCRIPTION
**Pull request by cairin**

### CODE REVIEW

**Comment by maxvipon** [comment]
This helps with API 28. Thanks!

**Comment by moconnell9** [comment]
Please support androidx! My team has no choice but to use it. Thanks :)

**Comment by jachstet-sea** [comment]
Same here, this plugin has issues with API 28, which is required to upload apps. This PR fixes that, thanks! Please merge :)

**Comment by Boby** [comment]
is this already merged with the latest plugin? which versions if its merged?

**Comment by EddyVerbruggen** [comment]
published to npm (5.6.6)

**Comment by DustinBrett** [comment]
@EddyVerbruggen This update caused my builds to fail with the error `Program type already present: android.support.v4.media.MediaBrowserCompat$ConnectionCallback$ConnectionCallbackInternal`. Going back to 5.6.5 fixed the issue. I've read of another possible solution [here](https://stackoverflow.com/questions/51389533/program-type-already-present-android-support-v4-media-mediabrowsercompatcustom), but I would rather not have to do that unless it's totally necessary.

**Comment by andersborgabiro** [comment]
I get the same error when building with API 27 and 5.6.6 of the plugin using PGB. Maybe I misunderstand the scope of the error.

**Comment by EddyVerbruggen** [comment]
Maybe one of the others can chime in - I've only merged this of the relative high demand and thumbs up I saw.

**Comment by jachstet-sea** [comment]
Since we are using the AndroidX-branch, I'm happy to chime in. The problem is that you cannot mix plugins depending on the "legacy" android-support with plugins that used AndroidX. If you do, you will see build failures. As such, going from android-support to AndroidX is a breaking change and maybe should have been released as v6.0.0 instead. That way, most users won't be affected since their current version specification of ^5.X.X won't pull the one with AndroidX automatically.
So the easiest fix might be to unpublish v5.6.6 and to re-publish it as v6.0.0.

What we are doing in order to avoid mixing plugins using Android-Support with ones using AndroidX is to additionally use https://www.npmjs.com/package/cordova-plugin-androidx-adapter in out projects. @DustinBrett  and @andersborgabiro could you please test if your build works with v5.6.6 and the adapter plugin added as well? Thanks!

**Comment by andersborgabiro** [comment]
It builds with this, that should pick 5.6.6:
    <plugin name="cordova-plugin-x-socialsharing"/>
    <plugin name="cordova-plugin-androidx-adapter"/>

I don't have anything newer than Android 7 though, so I can't test.

**Comment by EddyVerbruggen** [comment]
Note that one can't unpublish a release on npm, but reverting and publishing 5.6.7 is no problem, then release 6.0.0 if there is no alternative.

**Comment by jachstet-sea** [comment]
Agreed, if unpublishing is not possible, that would be the way to go. Then everyone experiencing build failures due to 5.6.6 should be okay and people requiring AndroidX can use v6.x

**Comment by EddyVerbruggen** [comment]
@jachstet-sea OK, this change has been reverted in 5.6.7, and re-applied in 6.0.0.

I added a note at the top of the readme and both have been pushed to npm.

**Comment by DustinBrett** [comment]
I was not able to pull 5.6.7 recently in npm. Using 5.6.5 for now still.

**Comment by DustinBrett** [comment]
@EddyVerbruggen The reason I couldn't get 5.6.7 is I had my package.json pointing directly to this GitHub repo, and this repo doesn't appear to have 5.6.7, whereas npm does.

**Comment by DustinBrett** [comment]
Now with 5.6.7 on npm I get another error `app/src/main/java/nl/xservices/plugins/FileProvider.java:4: error: package androidx.core.content does not exist`

**Comment by EddyVerbruggen** [comment]
@DustinBrett Sorry for that, I missed a file in the revert. 5.6.8 can now be grabbed from either GitHub or npm.

**Comment by roheel112233** [comment]
Program type already present: android.support.v4.media.MediaBrowserCompat$CustomActionCallback
I am getting this error while build an app anyone help how to fix this?

**Comment by AngelouzCastro** [comment]
How can I get it to work with Android 12?
